# Generated by Django 3.0.1 on 2019-12-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
