# Generated by Django 3.0.1 on 2019-12-31 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
